// AUTO-GENERATED by scripts/feature-content/compile.mjs — DO NOT EDIT. Source: docs/features-content/*.md
import type { FeaturePageProps } from '../pages/features/FeaturePageLayout';

export const generatedFeaturePages: Record<string, FeaturePageProps> = {
  "apply-kit": {
      "slug": "apply-kit",
      "metaTitle": "Apply Kit — Win Upwork Gigs With Proof | Dezygn",
      "metaDescription": "The Apply Kit reads an Upwork job and returns a brief read, a tailored cover letter, and ready-to-generate sample concepts — so you apply with proof of work instead of promises.",
      "eyebrow": "Apply Kit · Proof Before Pitch",
      "headline": "Turn a gig into a portfolio.",
      "intro": "Drop an Upwork job in and get the whole application back — the brief read, a tailored cover letter, and 3–5 sample concepts you can generate on the spot. Pitch with the work, not just words.",
      "image": {
          "src": "/assets/images/landing-v4/apply-kit/hero.png",
          "alt": "Opportunities feed with Build kit on each Upwork job card"
      },
      "stepsHeading": "From job post to proof.",
      "stepsBody": "One pipeline reads the gig, says what the client actually wants, drafts the letter, and hands you sample concepts ready to render. The samples are the moat — not the letter.",
      "steps": [
          {
              "title": "Open a gig",
              "body": "From the Opportunities feed, hit Build kit on any job card — it opens the kit as a full subpage inside the v2 shell, with a back button and Open on Upwork in the header."
          },
          {
              "title": "Read the brief",
              "body": "A 2-line brief teaser sits up top; Full brief & risks opens the complete analysis plus honest risk flags in an overlay, so you know what you're walking into."
          },
          {
              "title": "Edit the cover letter",
              "body": "The left column holds an editable cover letter — hook, your fit, free-sample close. Copy it, Regenerate it, or tweak the wording; edits persist on blur. Letter text is free."
          },
          {
              "title": "Generate the samples",
              "body": "The right column lists 3–5 sample concepts, each with a ready-to-run prompt. Pick a model, see the per-image cost, and render one — or Generate all in a single pass. Credits deduct as usual."
          },
          {
              "title": "Apply with proof",
              "body": "Save samples into a brand + campaign, mark the gig applied, and head to Upwork with the work in hand. You can also Refine in campaign to keep iterating in chat."
          }
      ],
      "capabilities": {
          "heading": "Everything the kit hands you.",
          "body": "A full application package, built from one job post, in seconds.",
          "items": [
              "Brief read — what the client actually wants, plus honest risk flags",
              "A tailored cover letter: hook, your fit, free-sample close — editable inline",
              "3–5 sample concepts, each with a ready-to-run image prompt",
              "Model picker and per-image cost, matched to the composer",
              "Generate all in one pass, or render concepts one at a time",
              "Save samples straight into a brand + campaign, or refine in chat"
          ]
      },
      "related": [
          {
              "label": "Outreach Factory",
              "description": "Drop in a CSV of leads and Outreach Factory finds each brand's product, picks the strongest visual argument, and generates a personalized proof-of-work image for every row — ready to export into your cold-email tool.",
              "to": "/features/outreach-factory"
          },
          {
              "label": "Opportunities",
              "description": "A daily feed of AI-photography jobs pulled straight from Upwork, scored for how well each one fits you — so you scan, spot the strong matches, and open the one worth pitching.",
              "to": "/features/opportunities"
          }
      ],
      "ctaHeadline": "Apply with the work in hand.",
      "ctaBody": "Stop writing proposals into the void. Read the brief, draft the letter, and bring the samples."
  },
  "awa-chat": {
      "slug": "awa-chat",
      "metaTitle": "Awa — Your AI Creative Director | Dezygn",
      "metaDescription": "Awa is Dezygn's conversational AI creative director: describe the outcome, attach references, ask for variations, and refine the winners. She writes the prompts and runs the shoot.",
      "eyebrow": "Awa · AI creative director",
      "headline": "Talk to your art director.",
      "intro": "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English.",
      "image": {
          "src": "/assets/images/landing-v4/awa-chat/hero.png",
          "alt": "Awa chat pane beside a spread of generated frames in the workspace"
      },
      "stepsHeading": "Brief her like a freelancer.",
      "stepsBody": "You describe the outcome in plain language; Awa turns it into optimized prompts, generates a spread, critiques the results, and refines the ones you pick. The craft is hers — the direction is yours.",
      "steps": [
          {
              "title": "Describe the outcome, not the syntax",
              "body": "Tell Awa what you want in plain English — 'a warm morning hero shot of this candle on a linen table, soft window light.' She writes the optimized prompt for you, so brief the result you're after instead of typing keyword soup."
          },
          {
              "title": "Attach the products and references she should use",
              "body": "Add ingredients to the message — your product photo, a logo, a reference frame — using the plus button or an @image mention. Awa builds the shot around exactly the assets you attach, and keeps your brand colors and rules in mind."
          },
          {
              "title": "Ask for a spread, then refine the winners",
              "body": "Ask for several variations at once ('give me five takes, vary the angle and props'), star the two or three that work, then refine only those — 'on the third one, lower the camera and warm the light.' Iterate by the word; don't re-roll the whole batch."
          },
          {
              "title": "Use Plan when you want a sketch first",
              "body": "Flip the composer to Plan and Awa talks through the approach before spending credits — angles, props, lighting. Flip to Act and she executes immediately. Use Plan for a new direction, Act when you already know the shot."
          },
          {
              "title": "Reply to a specific frame",
              "body": "Click a frame to reply to it directly, so Awa knows exactly which image you mean before you ask for an edit. 'Reply' pins that frame to your next message — no more 'the second one from the left.'"
          }
      ],
      "capabilities": {
          "heading": "What Awa does for you.",
          "body": "A real creative director on tap — not a text box that returns one image.",
          "items": [
              "Writes optimized, on-brand prompts from a plain-English brief",
              "Generates a spread and edits any frame with surgical instructions",
              "Critiques her own results for quality, fidelity, and brand fit",
              "Remembers your brand, products, and campaign rules across the session",
              "Imports reference images from a website straight into your ingredients",
              "Runs the loop: generate a spread, you pick the keepers, she refines them"
          ]
      },
      "related": [
          {
              "label": "Prompt Canvas",
              "description": "The prompt behind every frame, made readable — compare two frames word-by-word, edit the exact text, and resend it verbatim. Awa writes the words; you direct.",
              "to": "/features/prompt-canvas"
          }
      ],
      "ctaHeadline": "Hire a creative director that never sleeps.",
      "ctaBody": "Describe what you want, attach a reference, ask for variations. Awa runs the shoot — you call the shots."
  },
  "awa-video": {
      "slug": "awa-video",
      "metaTitle": "Awa Video — Storyboard Ads & Image-to-Video | Dezygn",
      "metaDescription": "Awa turns your images into short cinematic clips with audio — a single-image animate or a full storyboard ad (brief → character sheet → labeled panels → one clip), powered by Seedance 2.0.",
      "eyebrow": "Awa · Video",
      "headline": "Bring your best shots to life.",
      "intro": "Ask Awa to animate an image or direct a storyboard ad — a cinematic clip with audio, generated and played right in the chat.",
      "image": {
          "src": "/assets/images/landing-v4/awa-video/hero.png",
          "alt": "Awa's inline video player showing a storyboard ad with labeled panels in the workspace"
      },
      "stepsHeading": "From a still to a story.",
      "stepsBody": "Tell Awa what you want; she plans the storyboard, shows the cost, and brings it to life.",
      "steps": [
          {
              "title": "Ask Awa to animate",
              "body": "Say \\\"animate this\\\" or \\\"make a 15s ad for this product.\\\" Awa always shows a plan + the credit cost first — video is the most expensive operation, so nothing runs until you confirm."
          },
          {
              "title": "She directs the storyboard",
              "body": "For an ad she runs the director workflow: a creative brief, a character reference sheet, then burned-label panels (SCENE | TIME | ROLE) composited into one cinematic clip with audio."
          },
          {
              "title": "Watch it inline",
              "body": "The finished clip plays right in the chat with its own player — no download needed to review it."
          },
          {
              "title": "Take it further",
              "body": "From there, cut a 9:16 Reels/TikTok version, rebuild with new panels, generate a still hero shot, or have Awa draft the proposal copy to go with it."
          }
      ],
      "capabilities": {
          "heading": "What Awa can make.",
          "body": "Two modes, both conversational — no timeline to learn.",
          "items": [
              "Animate a single image into a short clip (with first→last-frame keyframing)",
              "Direct a full storyboard ad: brief → character sheet → labeled panels → one cinematic clip",
              "Automatic audio — music, SFX, and voice",
              "Up to 15s, 9 reference panels (@Image1..@Image9), any aspect ratio",
              "Plays inline in the chat; then cut a 9:16 version, rebuild panels, or draft the pitch"
          ]
      },
      "related": [
          {
              "label": "Awa",
              "description": "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English.",
              "to": "/features/awa-chat"
          },
          {
              "label": "Gallery",
              "description": "Every frame from every campaign lands here — filter to the ones you want, star the keepers, then share a clean review room with your client or export them in one zip.",
              "to": "/features/gallery"
          },
          {
              "label": "Prompt Canvas",
              "description": "The prompt behind every frame, made readable — compare two frames word-by-word, edit the exact text, and resend it verbatim. Awa writes the words; you direct.",
              "to": "/features/prompt-canvas"
          }
      ],
      "ctaHeadline": "Make the ad, not just the photo.",
      "ctaBody": "Win the brief with a moving proof-of-work — generated in the same chat as your stills."
  },
  "brands": {
      "slug": "brands",
      "metaTitle": "Brands — Organize Every Client in Dezygn | Dezygn",
      "metaDescription": "The Brands page is your client wall: one card per brand with its latest frames, campaign count, and quick actions. Create brands from a URL, open them to their campaigns, and search or sort the shelf.",
      "eyebrow": "Brands · Your clients, organized",
      "headline": "Every client, on one wall.",
      "intro": "Brands is your home wall — one card per client, each showing its latest work, its campaigns, and a way in. Create a brand, open it to its campaigns, and search or sort the whole shelf at a glance.",
      "image": {
          "src": "/assets/images/landing-v4/brands/hero.png",
          "alt": "The v2 Brands page — a grid of brand cards each previewing recent frames"
      },
      "stepsHeading": "From a wall of clients to the work.",
      "stepsBody": "A brand holds a client's colors, voice, and visual style; its card shows the latest frames and campaigns. Land on the wall, pick a brand, and you're one click from the work.",
      "steps": [
          {
              "title": "Read your brand wall",
              "body": "Each card is one client. The image mosaic is that brand's most recent frames; the line under it counts its campaigns and frames. The top of the page sums it all up — brands, campaigns, total frames."
          },
          {
              "title": "Create a new brand",
              "body": "Click New brand to open the import drawer. Paste a website URL and Dezygn reads the live site to fill colors, voice, and visual style — or fill it in by hand. (That drawer has its own walkthrough.)"
          },
          {
              "title": "Open a brand to its campaigns",
              "body": "Click a card to open the brand and see its campaigns. Or use the card buttons to jump straight to that brand's Gallery, or start a new Campaign under it."
          },
          {
              "title": "Search and sort the shelf",
              "body": "Search by brand name to filter the wall, flip Sort between Recently used and A–Z, and toggle Grid or List in the header to suit how you scan."
          }
      ],
      "capabilities": {
          "heading": "What the Brands wall gives you.",
          "body": "A single, scannable home for every client you create for.",
          "items": [
              "One card per brand, each previewing its most recent frames",
              "Live counts — brands, campaigns, and total frames — across the top",
              "Create a new brand from a website URL or by hand",
              "Open any brand to its campaigns, or jump straight to its gallery",
              "Search by brand name and sort by recently used or A–Z",
              "Grid or list view, switchable from the page header"
          ]
      },
      "related": [
          {
              "label": "Brand Import",
              "description": "Paste your website URL and Dezygn browses the live site to build a ready-to-use brand — colors, fonts, tone, and visual style — that Awa uses on every shot.",
              "to": "/features/new-brand-import"
          },
          {
              "label": "Awa",
              "description": "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English.",
              "to": "/features/awa-chat"
          }
      ],
      "ctaHeadline": "Give every client a home.",
      "ctaBody": "Build a brand once and every campaign, frame, and shoot lives under it — ready the moment you sit down to create."
  },
  "feedback": {
      "slug": "feedback",
      "metaTitle": "Feedback — Your Client Review Inbox | Dezygn",
      "metaDescription": "The Dezygn feedback inbox: visual review rounds and concept reviews in one queue, grouped by round, filtered by status, brand, and kind.",
      "eyebrow": "Feedback · Your review inbox",
      "headline": "Every client reaction, in one inbox.",
      "intro": "Feedback is the single place every reaction lands — visual review rounds and concept decisions, grouped by round, filterable by status, so nothing a client said gets lost.",
      "image": {
          "src": "/assets/images/landing-v4/feedback/hero.png",
          "alt": "The Dezygn feedback inbox listing review rounds"
      },
      "stepsHeading": "From shared link to clear next step.",
      "stepsBody": "When a client rates a frame or decides on a concept, it lands here — counted, grouped, and ready to act on without digging through email.",
      "steps": [
          {
              "title": "See everything waiting on you",
              "body": "The top of the page counts unread work, brands in view, and how many visual versus concept rounds are open — your whole review load at a glance."
          },
          {
              "title": "Filter down to what matters",
              "body": "Narrow the queue by status, review kind, or brand. Visual feedback and concept decisions share one list, so nothing hides in a separate tab."
          },
          {
              "title": "Act on a round",
              "body": "Each card can open the shared link, jump to its campaign, mark read, or archive. A 'needs tweaks' note can go straight into revision chat with Awa."
          }
      ],
      "capabilities": {
          "heading": "What the inbox gives you.",
          "body": "A triage surface for review work, not just a notification list.",
          "items": [
              "Visual rounds and concept decisions in the same queue",
              "Rounds grouped with reviewed / total progress and unread counts",
              "Filter by status, review kind, and brand",
              "Open the share round, jump to the campaign, mark read, or archive",
              "Hand a 'needs tweaks' note straight into revision chat with Awa"
          ]
      },
      "related": [
          {
              "label": "Gallery",
              "description": "Every frame from every campaign lands here — filter to the ones you want, star the keepers, then share a clean review room with your client or export them in one zip.",
              "to": "/features/gallery"
          },
          {
              "label": "Awa",
              "description": "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English.",
              "to": "/features/awa-chat"
          }
      ],
      "ctaHeadline": "Never lose a client note again.",
      "ctaBody": "One inbox for every reaction — grouped, counted, and ready to act on."
  },
  "gallery-share": {
      "slug": "gallery-share",
      "metaTitle": "Share & Review — Client Review Rooms | Dezygn",
      "metaDescription": "Curate winners, share a stable client review link, and collect per-image approvals and comments on a clean, login-free, mobile-friendly page — then revise and re-share until approved.",
      "eyebrow": "Gallery · Client review",
      "headline": "Send a link. Get a decision.",
      "intro": "Star the winners in your gallery, share one clean review room, and let your client approve or comment image-by-image — feedback flows straight back to your workspace to revise and re-share until it's approved.",
      "image": {
          "src": "/assets/images/landing-v4/gallery-share/hero.png",
          "alt": "v2 Gallery with starred winning frames ready to share"
      },
      "stepsHeading": "From gallery to green light.",
      "stepsBody": "One stable room link carries every round. Curate, send, and watch decisions come back — no logins, no email threads, no lost feedback.",
      "steps": [
          {
              "title": "Curate the winners",
              "body": "In the Gallery, star the frames you want the client to see. Selected frames are what the review room shows — so you control the edit."
          },
          {
              "title": "Hit Share",
              "body": "Open the share drawer from the Gallery. Dezygn reuses the campaign's existing review room when there is one, or spins up a fresh one."
          },
          {
              "title": "Copy the room link",
              "body": "One stable room link covers every round you ever send for this client. Copy it and drop it into your own email or message."
          },
          {
              "title": "Your client decides",
              "body": "They open a clean page — no login — and Select, Needs tweak, or Pass on each image, with a note where it helps."
          },
          {
              "title": "Feedback lands back home",
              "body": "Every decision flows into your Feedback inbox and the campaign chat, where you can send a frame straight into a revision and re-share the next round."
          }
      ],
      "capabilities": {
          "heading": "What the review room does.",
          "body": "A client-facing review page that does the chasing for you.",
          "items": [
              "Star and curate the winning frames straight from the gallery",
              "Share one stable room link that holds every review round",
              "Clients approve, request tweaks, or pass — per image, no login",
              "A clean, warm review page that works on any phone",
              "Feedback returns to your workspace so you can revise and re-share"
          ]
      },
      "related": [
          {
              "label": "Awa",
              "description": "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English.",
              "to": "/features/awa-chat"
          }
      ],
      "ctaHeadline": "Stop chasing approvals.",
      "ctaBody": "Send one link, get a clear decision on every frame, and revise from the exact feedback — all in one loop."
  },
  "gallery": {
      "slug": "gallery",
      "metaTitle": "Gallery — Browse, Curate, Share & Export Frames | Dezygn",
      "metaDescription": "The Gallery is the home for every frame you've generated: filter by brand, campaign, tag, favorites, or feedback status; resize the tiles; favorite and select; then share a client review room or export to zip.",
      "eyebrow": "Gallery · Every frame you've made",
      "headline": "All your shots, in one beautiful contact sheet.",
      "intro": "Every frame from every campaign lands here — filter to the ones you want, star the keepers, then share a clean review room with your client or export them in one zip.",
      "image": {
          "src": "/assets/images/landing-v4/gallery/hero.png",
          "alt": "The v2 Gallery full of generated Lumère product frames"
      },
      "stepsHeading": "From contact sheet to client.",
      "stepsBody": "Browse everything you've made, narrow it down to the winners, and move them onward — into a review room or a download — without leaving the page.",
      "steps": [
          {
              "title": "Browse your gallery",
              "body": "Every frame you've generated shows up here as a contact sheet. Cycle tile size (S / L / XL) or group by campaign to scan faster."
          },
          {
              "title": "Filter to find the shots",
              "body": "Narrow by brand, campaign, tag, favorites, or feedback status — Selected, Needs tweak, Pass — and sort newest or oldest."
          },
          {
              "title": "Favorite & select",
              "body": "Tap the star to favorite a keeper. Hit Select to pick several frames at once — that selection is what you share, export, or turn into a video or collage."
          },
          {
              "title": "Share a review room",
              "body": "With frames selected, hit Share. Dezygn reuses this campaign's review room or spins up a fresh one and hands you one stable client link."
          },
          {
              "title": "Export the set",
              "body": "Prefer files? Export zips the current filtered view — or just your selection — into one download."
          }
      ],
      "capabilities": {
          "heading": "What the gallery gives you.",
          "body": "One place that holds every frame and every way you'd want to act on it.",
          "items": [
              "Browse every frame you've generated, across all campaigns",
              "Filter by brand, campaign, tag, favorites, or feedback status — and sort newest/oldest",
              "Change tile size (S / L / XL) and group by campaign or view as a flat grid",
              "Star favorites and multi-select frames to act on a batch",
              "Share a stable client review room, or export the set as a single zip"
          ]
      },
      "related": [
          {
              "label": "Share & Review",
              "description": "Star the winners in your gallery, share one clean review room, and let your client approve or comment image-by-image — feedback flows straight back to your workspace to revise and re-share until it's approved.",
              "to": "/features/gallery-share"
          },
          {
              "label": "Awa",
              "description": "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English.",
              "to": "/features/awa-chat"
          }
      ],
      "ctaHeadline": "Find the frame. Send the link.",
      "ctaBody": "Every shot you've made, one filter away — then straight to your client or your desktop."
  },
  "home": {
      "slug": "home",
      "metaTitle": "Home — Your Studio Dashboard | Dezygn",
      "metaDescription": "The Dezygn home dashboard: favorite frames, recent campaigns, an action queue for review work, and your brands — all on one screen.",
      "eyebrow": "Home · Your studio at a glance",
      "headline": "Walk in and pick up where you left off.",
      "intro": "Home is your studio's front door — favorite frames up top, the campaign you were just in one tap away, an action queue for anything waiting on you, and every brand within reach.",
      "image": {
          "src": "/assets/images/landing-v4/home/hero.png",
          "alt": "The Dezygn home dashboard with favorites, action queue, and brands"
      },
      "stepsHeading": "One screen, everything in reach.",
      "stepsBody": "No hunting for where you left off. Home surfaces your best frames, your last campaign, your review queue, and your brands the moment you land.",
      "steps": [
          {
              "title": "See your best work first",
              "body": "The Favorites mosaic up top holds every frame you've starred. Click any tile to jump straight back to the campaign it came from."
          },
          {
              "title": "Clear your action queue",
              "body": "The Action queue on the right collects review rounds and concept decisions waiting on you. Tap a row to open the feedback or campaign behind it."
          },
          {
              "title": "Pick up where you left off",
              "body": "Below the fold, your recently opened campaigns and your brands sit side by side — one tap back into any workspace."
          }
      ],
      "capabilities": {
          "heading": "What lives on Home.",
          "body": "A glanceable studio dashboard, not a blank start page.",
          "items": [
              "Favorites mosaic — your starred frames, click straight back to the source campaign",
              "Action queue — review rounds and concepts waiting on you",
              "Pick up where you left off — your most recently opened campaigns",
              "Brands at a glance — a thumbnail wall per brand with campaign counts",
              "First-mile checklist and product tour for new accounts"
          ]
      },
      "related": [
          {
              "label": "Brands",
              "description": "Brands is your home wall — one card per client, each showing its latest work, its campaigns, and a way in. Create a brand, open it to its campaigns, and search or sort the whole shelf at a glance.",
              "to": "/features/brands"
          },
          {
              "label": "Gallery",
              "description": "Every frame from every campaign lands here — filter to the ones you want, star the keepers, then share a clean review room with your client or export them in one zip.",
              "to": "/features/gallery"
          }
      ],
      "ctaHeadline": "Open the door to your studio.",
      "ctaBody": "Every brand, campaign, and frame — one screen away."
  },
  "ingredients": {
      "slug": "ingredients",
      "metaTitle": "Ingredients — Your Brand's Asset Library | Dezygn",
      "metaDescription": "Ingredients are the products, logos, and reference images Awa generates from. Upload, import from a URL, draw, tag, filter, and attach them to any prompt with @.",
      "eyebrow": "Ingredients · Your brand's asset library",
      "headline": "The real things your shots are built from.",
      "intro": "A per-brand library of the products, logos, and references Awa actually uses — upload them, import from a URL, or draw your own, then drop them into any prompt with @.",
      "image": {
          "src": "/assets/images/landing-v4/ingredients/hero.png",
          "alt": "The Ingredients tab — a masonry mosaic of product and reference images for the brand"
      },
      "stepsHeading": "Bring your own pixels.",
      "stepsBody": "A real product photo beats a paragraph of description. The Ingredients tab is where your brand's source assets live — ready to attach to any shot.",
      "steps": [
          {
              "title": "Open the Ingredients tab",
              "body": "In any campaign workspace, switch to the Ingredients tab. It's brand-wide — everything here belongs to the brand named in the header, ready for any campaign under it."
          },
          {
              "title": "Add your assets",
              "body": "Drag files anywhere onto the tab, or use Upload. Paste a link to import from a URL, Shopify, or Pinterest. Or hit Draw to sketch a new ingredient on a focused canvas and save it."
          },
          {
              "title": "Tag and filter",
              "body": "Tags are yours to manage. Use the # Tags toggle to reveal a frequency-sorted chip strip and narrow the grid, or search by name. Need help? AI analyze tags a selection for you."
          },
          {
              "title": "Attach with @",
              "body": "In the chat composer, type @ (or use the plus button) to attach an ingredient to your message. Awa builds the shot around exactly the assets you pick — up to 10 per message."
          },
          {
              "title": "Prep before you save",
              "body": "Open an ingredient's detail drawer and choose Open Prep to crop, remove the background, or upscale. Apply it and Save as new — your original source stays untouched."
          }
      ],
      "capabilities": {
          "heading": "Everything your shots are made of.",
          "body": "One brand-wide library, gathered however suits you, and always a chip away from the prompt.",
          "items": [
              "Upload products & references — drag-and-drop anywhere, up to 10 files at once",
              "Import straight from a URL, Shopify product page, or Pinterest",
              "Draw your own ingredient on a focused canvas, then save it",
              "Tag and filter — your tags, plus an optional AI analyze pass",
              "Attach any ingredient to a prompt with @ so Awa builds around the real thing",
              "Prep an ingredient — crop, remove background, upscale — and save it back"
          ]
      },
      "related": [
          {
              "label": "Awa",
              "description": "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English.",
              "to": "/features/awa-chat"
          },
          {
              "label": "Product Prep",
              "description": "A quick crop-and-enhance station for your product shots — frame it right, sharpen and clean it up, then save it back as an ingredient Awa can build from.",
              "to": "/features/product-prep"
          }
      ],
      "ctaHeadline": "Give Awa the real thing.",
      "ctaBody": "Stop describing your product. Upload it, draw it, or import it — then attach it and let Awa shoot."
  },
  "new-brand-import": {
      "slug": "new-brand-import",
      "metaTitle": "Brand Import — Build a Brand from Your Website | Dezygn",
      "metaDescription": "Paste a URL and Dezygn reads your live site to extract colors, fonts, voice, and visual style into an editable brand profile — or build one by hand.",
      "eyebrow": "Brands · Website import",
      "headline": "Your brand, captured in seconds.",
      "intro": "Paste your website URL and Dezygn browses the live site to build a ready-to-use brand — colors, fonts, tone, and visual style — that Awa uses on every shot.",
      "image": {
          "src": "/assets/images/landing-v4/new-brand-import/hero.png",
          "alt": "New brand drawer with the import-from-website field"
      },
      "stepsHeading": "From a URL to a brand.",
      "stepsBody": "No questionnaires, no swatches to hunt down. Paste your site, watch it read the real pages, then review and save. Prefer to build it yourself? Every field stays hand-editable.",
      "steps": [
          {
              "title": "Open New Brand",
              "body": "From the Brands area, start a new brand. The brand drawer slides in with an Import-from-website field at the top."
          },
          {
              "title": "Paste a website URL",
              "body": "Drop in your site (e.g. https://yourbrand.com) and hit Analyze. Anything public works — homepage, product, and about pages all get read."
          },
          {
              "title": "Watch it read your site",
              "body": "Dezygn actually browses the live site — opening the homepage, product pages, and about page. A deep read takes 60–120 seconds; you'll see staged progress while it works."
          },
          {
              "title": "Review and edit the fingerprint",
              "body": "The form fills with evidence-based values — colors, font, archetype, audience, and a rich visual style. Adjust anything that doesn't feel right; nothing is locked."
          },
          {
              "title": "Save (or build it by hand)",
              "body": "Save to store the brand and its fingerprint. No site to import? Skip the URL field and fill the form manually — the brand works exactly the same."
          }
      ],
      "capabilities": {
          "heading": "What the import captures.",
          "body": "A real read of your live site — not a logo grab — distilled into an editable brand fingerprint.",
          "items": [
              "Colors pulled from the actual site, normalized to clean hex",
              "Font style and typographic feel",
              "Brand voice, personality archetype, and target audience",
              "A generation-ready visual style description (key materials, lighting, mood)",
              "Editable preview — every field is yours to adjust before saving",
              "The saved fingerprint feeds Awa as context on every generation"
          ]
      },
      "related": [
          {
              "label": "Awa",
              "description": "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English.",
              "to": "/features/awa-chat"
          }
      ],
      "ctaHeadline": "Bring your brand in one paste.",
      "ctaBody": "Skip the setup forms. Paste your site, tweak what you like, and start creating on-brand."
  },
  "opportunities": {
      "slug": "opportunities",
      "metaTitle": "Opportunities — Your Daily AI-Photography Gig Feed | Dezygn",
      "metaDescription": "The Opportunities page is a daily feed of AI-photography jobs from Upwork, each scored for fit. Scan the strong matches, filter by status, and open a gig to build a full Apply Kit.",
      "eyebrow": "Opportunities · Your daily gig feed",
      "headline": "The right gigs, ranked and waiting.",
      "intro": "A daily feed of AI-photography jobs pulled straight from Upwork, scored for how well each one fits you — so you scan, spot the strong matches, and open the one worth pitching.",
      "image": {
          "src": "/assets/images/landing-v4/opportunities/hero.png",
          "alt": "Opportunities feed of AI-photography Upwork gigs, each card scored for fit"
      },
      "stepsHeading": "Open it daily, scan, and pick one.",
      "stepsBody": "Every job is pulled from Upwork, scored for fit, and laid out as a clean feed. You read the score, scan for new strong matches, and open the gig that's worth your pitch.",
      "steps": [
          {
              "title": "Your daily gig feed",
              "body": "Open /v2/opportunities for a feed of AI-photography jobs pulled from Upwork — freshest posts first. It's a shared pool, so there are always gigs to scan; hit Refresh jobs to pull the latest."
          },
          {
              "title": "Read the fit score",
              "body": "Every card carries a fit score — how well that job matches AI-photography work. Cards scoring 90+ get an accent border and a 'Strong match' badge. The info icon reveals the AI's reasoning."
          },
          {
              "title": "Filter and scan",
              "body": "Tabs split Open, Applied, and Skipped so you only see what's actionable. Scan for new strong matches; Stats and video jobs stay tucked away so the gig cards lead the page."
          },
          {
              "title": "Open a gig → Apply Kit",
              "body": "Hit Build kit on any card to turn the gig into a full application package — a brief read, a tailored cover letter, and ready-to-generate sample concepts. Open jumps straight to the Upwork post."
          }
      ],
      "capabilities": {
          "heading": "What the feed gives you.",
          "body": "A curated job board that does the triage for you — so you spend your time pitching, not searching.",
          "items": [
              "A daily feed of AI-photography gigs pulled from Upwork, freshest first",
              "A fit score on every card — how well the job matches your work",
              "Strong matches (90+) get an accent border and a 'Strong match' badge",
              "Budget, client spend, payment-verified status, and location at a glance",
              "Tabs for Open, Applied, and Skipped so nothing slips",
              "Build kit on any card to turn the gig into a full application package"
          ]
      },
      "related": [
          {
              "label": "Apply Kit",
              "description": "Drop an Upwork job in and get the whole application back — the brief read, a tailored cover letter, and 3–5 sample concepts you can generate on the spot. Pitch with the work, not just words.",
              "to": "/features/apply-kit"
          },
          {
              "label": "Outreach Factory",
              "description": "Drop in a CSV of leads and Outreach Factory finds each brand's product, picks the strongest visual argument, and generates a personalized proof-of-work image for every row — ready to export into your cold-email tool.",
              "to": "/features/outreach-factory"
          }
      ],
      "ctaHeadline": "Find your next client before lunch.",
      "ctaBody": "Stop scrolling Upwork for the one good gig. Open the feed, read the scores, and pitch the match."
  },
  "outreach-factory": {
      "slug": "outreach-factory",
      "metaTitle": "Outreach Factory — Bulk Personalized Proof-of-Work Visuals | Dezygn",
      "metaDescription": "Turn a CSV lead list into personalized product visuals at scale: product discovery, a creative strategist that picks the winning angle per brand, batch image generation, winner review, and an Instantly-ready export.",
      "eyebrow": "Outreach Factory · Proof before pitch",
      "headline": "Show every prospect their own product, reimagined.",
      "intro": "Drop in a CSV of leads and Outreach Factory finds each brand's product, picks the strongest visual argument, and generates a personalized proof-of-work image for every row — ready to export into your cold-email tool.",
      "image": {
          "src": "/assets/images/landing-v4/outreach-factory/hero.png",
          "alt": "Outreach Factory batch dashboard with lead counts and generation actions"
      },
      "stepsHeading": "From a CSV row to a winning image.",
      "stepsBody": "Import a lead list, let discovery find each prospect's product, and watch the strategist pick the most persuasive visual for every brand — then review winners and export.",
      "steps": [
          {
              "title": "Import your lead list",
              "body": "Upload a CSV from /v2/outreach. Each row needs an email plus a domain or website. Add company, product URL, or founder URL columns to sharpen discovery."
          },
          {
              "title": "Discover the product",
              "body": "Discovery visits each lead's site, finds the hero product and images, and collects a factual brand fingerprint — colors, materials, photography style — to brief the strategist."
          },
          {
              "title": "Let the strategist choose the angle",
              "body": "For every brand the Creative Strategist scores hero product, lifestyle, and ad-creative modes and picks the strongest visual argument — no dropdown to babysit."
          },
          {
              "title": "Bulk-generate visuals",
              "body": "Hit Discover + generate. Two candidates run per lead, 2 leads at a time, each built from the prospect's own product image. Watch progress in the run log."
          },
          {
              "title": "Review winners and export",
              "body": "Compare each candidate against the original product shot, pick a winner per lead, and export an Instantly-ready CSV with an email-safe image URL per row."
          }
      ],
      "capabilities": {
          "heading": "What the factory does for you.",
          "body": "Personalization at list scale — every prospect gets an image made from their own product, not a template.",
          "items": [
              "Import a lead list (CSV) — map company, domain, email, and optional product/founder URLs",
              "Auto-discover each brand's hero product, images, and brand fingerprint from their site",
              "A creative strategist picks the strongest visual mode per brand: hero product, lifestyle, or ad creative",
              "Bulk-generate two personalized candidates per lead, 2 leads and 2 candidates at a time",
              "Review candidates against the original, pick winners, and export an Instantly-ready CSV"
          ]
      },
      "related": [
          {
              "label": "Apply Kit",
              "description": "Drop an Upwork job in and get the whole application back — the brief read, a tailored cover letter, and 3–5 sample concepts you can generate on the spot. Pitch with the work, not just words.",
              "to": "/features/apply-kit"
          },
          {
              "label": "Share & Review",
              "description": "Star the winners in your gallery, share one clean review room, and let your client approve or comment image-by-image — feedback flows straight back to your workspace to revise and re-share until it's approved.",
              "to": "/features/gallery-share"
          }
      ],
      "ctaHeadline": "Make the proof before you make the pitch.",
      "ctaBody": "Stop sending the same cold email everyone ignores. Send a real image of their product — at scale."
  },
  "product-prep": {
      "slug": "product-prep",
      "metaTitle": "Product Prep — Crop & Enhance Product Photos | Dezygn",
      "metaDescription": "Prep raw product photos before generation: crop and reframe, sharpen, clean up, and upscale with a before/after compare, then save back as a fresh ingredient.",
      "eyebrow": "Product Prep · Clean it up first",
      "headline": "Get the product photo camera-ready.",
      "intro": "A quick crop-and-enhance station for your product shots — frame it right, sharpen and clean it up, then save it back as an ingredient Awa can build from.",
      "image": {
          "src": "/assets/images/landing-v4/product-prep/hero.png",
          "alt": "Product Prep workspace with a product photo loaded for cropping and enhancement"
      },
      "stepsHeading": "From raw upload to ready ingredient.",
      "stepsBody": "Open prep on any ingredient, frame it, clean it up, and save it back. The original stays untouched — your prepped version becomes a new ingredient.",
      "steps": [
          {
              "title": "Open an ingredient",
              "body": "In the Ingredients tab, click any product asset to open its detail drawer, then hit *Open Prep* to enter the full-canvas prep workspace."
          },
          {
              "title": "Crop and frame",
              "body": "Drag the crop handles to reframe the shot, or resize with the aspect ratio locked so the product never stretches. These edits apply locally — instantly."
          },
          {
              "title": "Enhance it",
              "body": "Run *Upscale* to sharpen and add resolution, or *Remove background* to clean up clutter and isolate the product. Awa's image engine does the work."
          },
          {
              "title": "Compare before / after",
              "body": "Every enhancement opens a before/after slider with Original and Upscaled (or BG Removed) labels. Drag to judge it, then *Use this version* or *Discard*."
          },
          {
              "title": "Save back",
              "body": "*Save as new* writes a fresh ingredient tagged *prepped* — your original source stays intact, and the clean version is ready to attach in chat."
          }
      ],
      "capabilities": {
          "heading": "What prep gives you.",
          "body": "Everything you need to make a phone snapshot look like a product still — without leaving Dezygn.",
          "items": [
              "Open prep straight from an ingredient's detail drawer",
              "Crop and reframe to the composition you actually want",
              "Resize with the aspect ratio locked so nothing stretches",
              "Enhance — sharpen, clean up the background, and upscale",
              "Before / after slider so you only keep a real improvement",
              "Save back as a new ingredient; the source asset is preserved"
          ]
      },
      "related": [
          {
              "label": "Ingredients",
              "description": "A per-brand library of the products, logos, and references Awa actually uses — upload them, import from a URL, or draw your own, then drop them into any prompt with @.",
              "to": "/features/ingredients"
          },
          {
              "label": "Awa",
              "description": "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English.",
              "to": "/features/awa-chat"
          }
      ],
      "ctaHeadline": "Start every shot from a clean source.",
      "ctaBody": "A blurry, cluttered product photo drags down every frame built on it. Fix it once, here."
  },
  "prompt-canvas": {
      "slug": "prompt-canvas",
      "metaTitle": "Prompt Canvas — Read, Diff & Edit AI Prompts | Dezygn",
      "metaDescription": "The Prompt Canvas makes the prompt a first-class citizen: a sentence-spaced reading view, frame-to-frame word diff, and verbatim resend with enhancement off.",
      "eyebrow": "Prompt Canvas · Tao of the Prompt",
      "headline": "Direct the shot, not the syntax.",
      "intro": "The prompt behind every frame, made readable — compare two frames word-by-word, edit the exact text, and resend it verbatim. Awa writes the words; you direct.",
      "image": {
          "src": "/assets/images/landing-v4/prompt-canvas/hero.png",
          "alt": "Prompt Canvas reading view inside the workspace"
      },
      "stepsHeading": "From frame to frame.",
      "stepsBody": "The prompt sits on the canvas — readable, comparable, editable, resendable. No more guessing what changed between two shots.",
      "steps": [
          {
              "title": "Open the canvas",
              "body": "Hit the Prompt toggle in the workspace action rail, or click the prompt excerpt in any frame's info drawer."
          },
          {
              "title": "Read it like prose",
              "body": "One sentence per line in a serif reading view. [image1] tokens become chips. Flip Raw for a byte-exact copy."
          },
          {
              "title": "Compare two frames",
              "body": "Pick a second frame from the strip — you get both thumbnails plus one merged prompt with a word-level diff."
          },
          {
              "title": "Edit and resend",
              "body": "Edit the raw text; the send button shows an 'N words changed' badge and dispatches your wording verbatim."
          }
      ],
      "capabilities": {
          "heading": "What the canvas gives you.",
          "body": "More than a text box — a place to actually read and reason about prompts.",
          "items": [
              "Sentence-per-line reading view at a comfortable measure",
              "[image] reference tokens rendered as inline chips",
              "Word-level diff between any two frames — green adds, red deletes",
              "Edit the raw text and resend verbatim with enhancement off",
              "Copy, Use as reference, Rerun, Compare, and a Raw toggle"
          ]
      },
      "related": [
          {
              "label": "Awa",
              "description": "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English.",
              "to": "/features/awa-chat"
          }
      ],
      "ctaHeadline": "Take the wheel on every prompt.",
      "ctaBody": "Stop gambling on loose wording. Read it, diff it, resend it — exactly."
  },
  "recipes": {
      "slug": "recipes",
      "metaTitle": "Recipes — Reusable AI Shot Templates | Dezygn",
      "metaDescription": "Recipes are saved prompt-and-ingredient compositions. Browse one, fill its ingredient slots with your product, and generate a consistent on-brand shot in seconds.",
      "eyebrow": "Recipes · Reusable shot formulas",
      "headline": "Pour your product into a proven shot.",
      "intro": "Reusable prompt-and-ingredient compositions: browse a recipe, drop your product into its slots, and let Awa compose the shot the same winning way every time.",
      "image": {
          "src": "/assets/images/landing-v4/recipes/browser.png",
          "alt": "Recipe picker showing a searchable list of shot formulas"
      },
      "stepsHeading": "Pick the formula, add your product.",
      "stepsBody": "A recipe already knows the subject, lighting, environment, and camera. You only supply the ingredients — your product, your logo, your model — and generate.",
      "steps": [
          {
              "title": "Open the recipe browser",
              "body": "In the chat composer's Add panel, choose Recipes to open the browser — a grid of shot formulas with search and tag filters."
          },
          {
              "title": "Choose a recipe",
              "body": "Pick one from the grid by its thumbnail. The composer swaps into recipe mode and shows the recipe's ingredient slots and guided composition."
          },
          {
              "title": "Fill the ingredient slots",
              "body": "Drop your product, logo, or model into each slot. Required slots are flagged — the send button tells you which one is still missing."
          },
          {
              "title": "Tune the composition",
              "body": "Adjust the guided parameters — subject, action, environment, lighting, camera — to steer the look without rewriting the whole prompt."
          },
          {
              "title": "Generate",
              "body": "Send it. Awa composes the prompt from the recipe and your slots, then generates the shot. The recipe panel clears so you're back in normal chat."
          }
      ],
      "capabilities": {
          "heading": "What a recipe gives you.",
          "body": "More than a starter prompt — a reusable composition that stays consistent shot after shot.",
          "items": [
              "A browsable library of shot formulas with thumbnail previews, search, and tag filters",
              "Ingredient slots that tell you exactly what to drop in (product photo, logo, model)",
              "Guided shot composition — subject, action, environment, lighting, camera",
              "Your slot images flow in as normal chat attachments and resolve for later Awa turns",
              "Save your own private recipes to reuse a look across every campaign"
          ]
      },
      "related": [
          {
              "label": "Awa",
              "description": "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English.",
              "to": "/features/awa-chat"
          },
          {
              "label": "Prompt Canvas",
              "description": "The prompt behind every frame, made readable — compare two frames word-by-word, edit the exact text, and resend it verbatim. Awa writes the words; you direct.",
              "to": "/features/prompt-canvas"
          }
      ],
      "ctaHeadline": "Stop rewriting the same shot.",
      "ctaBody": "Capture the formula once, reuse it forever — drop in the product and go."
  },
  "settings": {
      "slug": "settings",
      "metaTitle": "Settings — Your Account Hub | Dezygn",
      "metaDescription": "The Dezygn account hub: plan and credits, team and watermark, profile, referrals, and support — each on its own tab with deep-linkable URLs.",
      "eyebrow": "Settings · Your account hub",
      "headline": "Plan, team, and profile — all in one place.",
      "intro": "Settings is your account hub: see your plan and credits, manage your team and share-page watermark, edit your profile, grab your referral link, and reach support.",
      "image": {
          "src": "/assets/images/landing-v4/settings/hero.png",
          "alt": "The Dezygn settings page with Plan, Team, Profile, Referrals, and Support tabs"
      },
      "stepsHeading": "Everything about your account, by tab.",
      "stepsBody": "Plan, team, profile, referrals, support — five tabs, each deep-linkable, so account management isn't buried in a single narrow column anymore.",
      "steps": [
          {
              "title": "Check plan and credits",
              "body": "The Plan & credits tab shows your subscription, your monthly, flex, and total balances, Flex-pack top-ups, and a link to the billing portal."
          },
          {
              "title": "Set up your team",
              "body": "The Team tab holds your team name, an invite link, the member list, and your share-page watermark — upload or replace it and toggle it on by default."
          },
          {
              "title": "Profile, referrals, and support",
              "body": "Edit your display name and password on Profile, copy your referral link with its conversion stats, and reach the Help Center or email from Support."
          }
      ],
      "capabilities": {
          "heading": "What you can manage here.",
          "body": "The full account surface — billing, team, identity, and growth.",
          "items": [
              "Plan & credits — subscription, monthly/flex/total balances, Flex packs, billing portal",
              "Team — name, invite link, share-page watermark, and member list",
              "Profile — display name, password, and your Upwork application profile",
              "Referrals — your link plus total / converted / pending stats",
              "Support — Help Center and email, one click away"
          ]
      },
      "related": [],
      "ctaHeadline": "Run your account on your terms.",
      "ctaBody": "Plan, team, profile, and referrals — all in one tabbed hub."
  },
  "variant-board": {
      "slug": "variant-board",
      "metaTitle": "Variant Board — A/B Test Your Shots One Variable at a Time | Dezygn",
      "metaDescription": "Pick a champion frame, add variant rows that each change exactly one thing — lighting, background, camera, style — generate the grid, and crown the winner.",
      "eyebrow": "Variant Board · Control vs. Variant",
      "headline": "Crown a champion, then change one thing.",
      "intro": "A/B testing for your shots: lock the frame that's winning, spin off variants that each change a single ingredient or setting, then compare the grid and crown a new champion.",
      "image": {
          "src": "/assets/images/landing-v4/variant-board/hero.png",
          "alt": "Variant Board with a locked champion frame"
      },
      "stepsHeading": "One champion, one variable at a time.",
      "stepsBody": "Good creative testing isn't 'generate ten and hope.' It's a control and a clean variable. The board makes that the path of least resistance.",
      "steps": [
          {
              "title": "Open the board",
              "body": "Select a frame, then hit the grid icon in the frame's action rail. The board opens to a contact sheet of every frame in the campaign."
          },
          {
              "title": "Crown a champion",
              "body": "Pick the frame that's clearly working and Promote to Champion. It locks on the left as your control — image plus an editable control prompt."
          },
          {
              "title": "Add a variant row",
              "body": "In the composer, choose ONE variable to change — lighting, background, camera, style — and write a short, concrete change description."
          },
          {
              "title": "Generate the grid",
              "body": "Each row generates from the champion, changing only its one clause. Fresh results auto-link to the oldest pending row."
          },
          {
              "title": "Crown the winner",
              "body": "Compare variants against the control. When one wins, save the champion as a Recipe to reuse the look — or promote a better frame and run again."
          }
      ],
      "capabilities": {
          "heading": "What the board gives you.",
          "body": "A disciplined experiment surface, not just another grid of guesses.",
          "items": [
              "Promote any generated frame to champion — your locked control",
              "Add variant rows, each pinned to one variable: lighting, background, action, subject, camera, style, brand accent",
              "Write a one-line change description per row — concrete beats vague",
              "Generate the grid; results auto-link back to the row that asked for them",
              "Compare against the champion and crown the winner — or save it as a Recipe"
          ]
      },
      "related": [
          {
              "label": "Prompt Canvas",
              "description": "The prompt behind every frame, made readable — compare two frames word-by-word, edit the exact text, and resend it verbatim. Awa writes the words; you direct.",
              "to": "/features/prompt-canvas"
          },
          {
              "label": "Awa",
              "description": "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English.",
              "to": "/features/awa-chat"
          }
      ],
      "ctaHeadline": "Stop guessing. Start testing.",
      "ctaBody": "Lock what works, change one thing, and let the grid tell you what's better."
  }
};

export const generatedFeatureIndex: { slug: string; title: string; eyebrow: string; subhead: string }[] = [
{
      "slug": "apply-kit",
      "title": "Apply Kit",
      "eyebrow": "Apply Kit · Proof Before Pitch",
      "subhead": "Drop an Upwork job in and get the whole application back — the brief read, a tailored cover letter, and 3–5 sample concepts you can generate on the spot. Pitch with the work, not just words."
    },
    {
      "slug": "awa-chat",
      "title": "Awa",
      "eyebrow": "Awa · AI creative director",
      "subhead": "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English."
    },
    {
      "slug": "awa-video",
      "title": "Awa Video",
      "eyebrow": "Awa · Video",
      "subhead": "Ask Awa to animate an image or direct a storyboard ad — a cinematic clip with audio, generated and played right in the chat."
    },
    {
      "slug": "brands",
      "title": "Brands",
      "eyebrow": "Brands · Your clients, organized",
      "subhead": "Brands is your home wall — one card per client, each showing its latest work, its campaigns, and a way in. Create a brand, open it to its campaigns, and search or sort the whole shelf at a glance."
    },
    {
      "slug": "feedback",
      "title": "Feedback",
      "eyebrow": "Feedback · Your review inbox",
      "subhead": "Feedback is the single place every reaction lands — visual review rounds and concept decisions, grouped by round, filterable by status, so nothing a client said gets lost."
    },
    {
      "slug": "gallery-share",
      "title": "Share & Review",
      "eyebrow": "Gallery · Client review",
      "subhead": "Star the winners in your gallery, share one clean review room, and let your client approve or comment image-by-image — feedback flows straight back to your workspace to revise and re-share until it's approved."
    },
    {
      "slug": "gallery",
      "title": "Gallery",
      "eyebrow": "Gallery · Every frame you've made",
      "subhead": "Every frame from every campaign lands here — filter to the ones you want, star the keepers, then share a clean review room with your client or export them in one zip."
    },
    {
      "slug": "home",
      "title": "Home",
      "eyebrow": "Home · Your studio at a glance",
      "subhead": "Home is your studio's front door — favorite frames up top, the campaign you were just in one tap away, an action queue for anything waiting on you, and every brand within reach."
    },
    {
      "slug": "ingredients",
      "title": "Ingredients",
      "eyebrow": "Ingredients · Your brand's asset library",
      "subhead": "A per-brand library of the products, logos, and references Awa actually uses — upload them, import from a URL, or draw your own, then drop them into any prompt with @."
    },
    {
      "slug": "new-brand-import",
      "title": "Brand Import",
      "eyebrow": "Brands · Website import",
      "subhead": "Paste your website URL and Dezygn browses the live site to build a ready-to-use brand — colors, fonts, tone, and visual style — that Awa uses on every shot."
    },
    {
      "slug": "opportunities",
      "title": "Opportunities",
      "eyebrow": "Opportunities · Your daily gig feed",
      "subhead": "A daily feed of AI-photography jobs pulled straight from Upwork, scored for how well each one fits you — so you scan, spot the strong matches, and open the one worth pitching."
    },
    {
      "slug": "outreach-factory",
      "title": "Outreach Factory",
      "eyebrow": "Outreach Factory · Proof before pitch",
      "subhead": "Drop in a CSV of leads and Outreach Factory finds each brand's product, picks the strongest visual argument, and generates a personalized proof-of-work image for every row — ready to export into your cold-email tool."
    },
    {
      "slug": "product-prep",
      "title": "Product Prep",
      "eyebrow": "Product Prep · Clean it up first",
      "subhead": "A quick crop-and-enhance station for your product shots — frame it right, sharpen and clean it up, then save it back as an ingredient Awa can build from."
    },
    {
      "slug": "prompt-canvas",
      "title": "Prompt Canvas",
      "eyebrow": "Prompt Canvas · Tao of the Prompt",
      "subhead": "The prompt behind every frame, made readable — compare two frames word-by-word, edit the exact text, and resend it verbatim. Awa writes the words; you direct."
    },
    {
      "slug": "recipes",
      "title": "Recipes",
      "eyebrow": "Recipes · Reusable shot formulas",
      "subhead": "Reusable prompt-and-ingredient compositions: browse a recipe, drop your product into its slots, and let Awa compose the shot the same winning way every time."
    },
    {
      "slug": "settings",
      "title": "Settings",
      "eyebrow": "Settings · Your account hub",
      "subhead": "Settings is your account hub: see your plan and credits, manage your team and share-page watermark, edit your profile, grab your referral link, and reach support."
    },
    {
      "slug": "variant-board",
      "title": "Variant Board",
      "eyebrow": "Variant Board · Control vs. Variant",
      "subhead": "A/B testing for your shots: lock the frame that's winning, spin off variants that each change a single ingredient or setting, then compare the grid and crown a new champion."
    }
];
