// AUTO-GENERATED by scripts/feature-content/compile.mjs — DO NOT EDIT. Source: docs/features-content/*.md
import type { HelpArticle } from './help';

export const generatedHelpArticles: Record<string, HelpArticle[]> = {
  "winning-clients": [
    {
      slug: "apply-kit",
      title: "Apply Kit",
      description: "Drop an Upwork job in and get the whole application back — the brief read, a tailored cover letter, and 3–5 sample concepts you can generate on the spot. Pitch with the work, not just words.",
      updatedAt: "2026-06-13",
      blocks: [
      { type: 'img', src: "/assets/images/landing-v4/apply-kit/hero.png", alt: "Opportunities feed with Build kit on each Upwork job card", caption: "Every job card has Build kit." },
      { type: 'h2', text: "Overview" },
      { type: 'p', text: "The Apply Kit turns an Upwork job posting into a ready-to-use application package — one pipeline, two doors. Open it from the Opportunities feed (Build kit on any job card) or from the *Proof-Before-Pitch* Chrome extension (Grab this job reads the open Upwork page). Out comes a brief read (what the client actually wants), a tailored cover letter, 3–5 sample image concepts with ready-to-run prompts, and honest risk flags." },
      { type: 'p', text: "The moat is the sample, not the letter. Anyone can write a proposal; the kit lets you walk in with the actual work. Each concept carries a prompt you can generate in one click through the normal image pipeline, so you pitch with proof instead of promises. Cover-letter text is free; sample generation spends credits like any image." },
      { type: 'h2', text: "How it works" },
      { type: 'ul', items: ["Open a gig. From the Opportunities feed, hit Build kit on any job card. The kit opens as a full subpage inside the v2 shell — sidebar and topbar stay put, with a back button and *Open on Upwork* in the header. (Reopening a kit never regenerates; it's cached per user + gig.)","Read the brief. A 2-line brief teaser sits up top. *Full brief & risks* opens the complete analysis plus honest risk flags in an overlay, so you know exactly what the client wants before you commit.","Edit the cover letter. The left column holds an editable letter with a fixed, proven shape: a remark on the post, your fit (skills from Dezygn + your profile), and a free-sample close. Copy, Regenerate, or tweak the wording — edits persist on blur, and the text is free.","Generate the samples. The right column lists the sample concepts, each with a ready-to-run prompt. Pick a Model (it mirrors the composer), see the per-image cost, and render one — or Generate all in a single confirmed pass. Save samples into a brand + campaign, or Refine in campaign to keep iterating in chat.","Apply with proof. Mark the gig applied, head to Upwork, and bring the work with you."] },
      { type: 'callout', variant: "tip", text: "Set up your Application Profile first (name, profile title, overview, portfolio links). With it, the letter positions you accurately; without it, the kit falls back to neutral wording and nudges you to fill it in." },
      { type: 'h2', text: "What's in a kit" },
      { type: 'ul', items: ["Brief read — a plain-language summary of what the client is actually asking for, separate from how the post is worded.","Risk flags — honest gaps or red flags worth knowing before you spend time applying.","Cover letter — hook-first, tailored to the post and your profile, with a free-sample close (it asks for the product, or offers to make it directly if the product is already in the post). Editable, copyable, regenerable.","3–5 sample concepts — each a distinct image idea with its own ready-to-run prompt, a model picker, and a visible per-image credit cost.","Generated samples — once rendered, they live on the kit and can be saved into a brand + campaign or handed to the campaign chat for refinement."] }
      ], related: ["outreach-factory","opportunities"],
    }
  ],
  "awa": [
    {
      slug: "awa-chat",
      title: "Awa",
      description: "Awa is the conversational AI creative director inside every campaign — she writes the prompts, runs the shoot, critiques the results, and remembers your brand, so you direct in plain English.",
      updatedAt: "2026-06-13",
      blocks: [
      { type: 'img', src: "/assets/images/landing-v4/awa-chat/hero.png", alt: "Awa chat pane beside a spread of generated frames in the workspace", caption: "Brief Awa in plain English; she runs the shoot." },
      { type: 'h2', text: "Overview" },
      { type: 'p', text: "Awa is the conversational AI creative director that lives inside every campaign. Instead of fiddling with prompt syntax, you brief her the way you'd brief a great freelancer: say what you want in plain English and she handles the craft — writing optimized prompts, running the shoot, editing frames, critiquing the results, and iterating until the work is client-ready. She reads your brand and remembers your campaign as you go, so the longer you work with her, the more she sounds like your studio. The direction stays yours; the heavy lifting is hers." },
      { type: 'h2', text: "How to talk to Awa" },
      { type: 'p', text: "The trick to getting great work out of Awa is simple: brief the outcome, not the syntax. Talk to her like an art director you trust." },
      { type: 'p', text: "Describe the result you want in plain language. \"A warm morning hero shot of this candle on a linen table, soft window light, lots of negative space\" tells Awa far more than a string of keywords. She translates your intent into an optimized, on-brand prompt — that's her job, not yours." },
      { type: 'p', text: "Attach the products and references she should use. Add your product photo, logo, or a reference frame to the message before you send it, using the plus button or an @image mention. Awa builds the shot around exactly the assets you attach, so a real reference beats a paragraph of description every time." },
      { type: 'p', text: "Generate a spread, then refine the winners. Ask for several variations at once — \"give me five takes, vary the angle and the props.\" Star the two or three that work and refine only those: \"on the third one, lower the camera and warm the light.\" This is the loop that produces good work: generate many, pick a few, refine the keepers. Iterate by the word, not by re-rolling the whole batch and hoping." },
      { type: 'p', text: "Reply to a specific frame when you mean a specific frame. Click a frame to pin it to your next message, so Awa knows precisely which image you're editing before you ask. It removes the ambiguity of \"the second one from the left.\"" },
      { type: 'p', text: "Use Plan when you want a sketch before spending credits, and Act when you already know the shot. In Plan mode Awa talks through her approach — angles, props, lighting — and waits for your go. In Act mode she executes immediately. Reach for Plan on a fresh direction; reach for Act when the brief is clear." },
      { type: 'p', text: "A few do's and don'ts worth keeping:" },
      { type: 'ul', items: ["Do describe the mood, lighting, surface, and framing — Awa loves direction.","Do correct her in plain words (\"too cold, push it warmer\") rather than rewriting the prompt yourself.","Don't paste keyword soup; she writes better prompts than a comma-separated list.","Don't re-roll a whole batch to fix one frame — refine that one frame instead."] },
      { type: 'h2', text: "What Awa can do" },
      { type: 'p', text: "Awa is more than a chat box — she's a creative director with a full toolkit she reaches for on your behalf:" },
      { type: 'ul', items: ["Writes optimized, on-brand prompts from a plain-English brief.","Generates images and, when asked, a whole spread of variations in one go.","Edits any frame with surgical, targeted instructions instead of starting over.","Critiques her own results, checking quality, product fidelity, and brand fit.","Reads your brand — colors, logos, style direction — and keeps it consistent.","Remembers the campaign as you work, and can save a correction as a lasting campaign rule so you never repeat yourself.","Imports reference images: point her at a website and she finds the right images and drops the ones you confirm into your ingredients.","Searches the web and gathers references when a shot needs them.","Generates product video for reveals and lifestyle motion when a campaign calls for it."] },
      { type: 'p', text: "You don't summon any of these by name — you describe what you want, and Awa picks the right tool for the job." }
      ], related: ["prompt-canvas"],
    }
  ],
  "feedback": [
    {
      slug: "feedback",
      title: "Feedback",
      description: "Feedback is the single place every reaction lands — visual review rounds and concept decisions, grouped by round, filterable by status, so nothing a client said gets lost.",
      updatedAt: "2026-06-13",
      blocks: [
      { type: 'img', src: "/assets/images/landing-v4/feedback/hero.png", alt: "The Dezygn feedback inbox listing review rounds", caption: "Every reaction, one inbox." },
      { type: 'h2', text: "Overview" },
      { type: 'p', text: "Feedback is your review inbox. When a client rates a frame on a shared link or decides on a brand concept, it lands here — not scattered across email threads. Visual review rounds and concept decisions sit in one queue, grouped by round, so you can see what's outstanding across every brand and campaign and act on it in one place." },
      { type: 'h2', text: "What you can do here" },
      { type: 'ul', items: ["Read the room at a glance. The page header counts unread work, brands in view, and how many visual versus concept rounds are open.","Filter the queue. Narrow by status, review kind (visual or concept), and brand — both kinds share one list, so nothing hides in a separate tab.","Act on each round. A round card can open the public share link, jump to the source campaign, mark read, or archive. Deletes go through a confirm step.","Turn feedback into a revision. A \"needs tweaks\" or \"pass\" note can be sent straight into revision chat — Awa picks up the reviewed frame and the client's words so you revise from context."] },
      { type: 'callout', variant: "tip", text: "The top-nav bell is the quick-triage version of this page; the full Feedback inbox is where you work the whole queue with filters and stats." }
      ], related: ["gallery","awa-chat"],
    },
    {
      slug: "gallery-share",
      title: "Share & Review",
      description: "Star the winners in your gallery, share one clean review room, and let your client approve or comment image-by-image — feedback flows straight back to your workspace to revise and re-share until it's approved.",
      updatedAt: "2026-06-13",
      blocks: [
      { type: 'img', src: "/assets/images/landing-v4/gallery-share/hero.png", alt: "v2 Gallery with starred winning frames ready to share", caption: "Curate winners, then share one room." },
      { type: 'h2', text: "Overview" },
      { type: 'p', text: "Share & Review is how a Dezygn project leaves your workspace and reaches a client. You curate the winning frames in the Gallery, share one clean review room, and your client makes a decision on each image — approve it, ask for a tweak, or pass — without ever creating an account. Those decisions flow straight back to your workspace, so you can revise from the exact feedback and send the next round on the same link. One link, one place, until the work is approved." },
      { type: 'h2', text: "How it works" },
      { type: 'ul', items: ["Curate the winners. In the Gallery, star the frames you want the client to see. The review room shows your selection, so the client only ever sees your best edit — not the whole contact sheet.","Share the room. Open the share drawer from the Gallery. Dezygn looks for an existing review room for that campaign (or brand) and reuses it as the next numbered round; if there isn't one yet, it creates a fresh room. Either way you get one stable room link.","The client decides, per image. They open the link — no login — and on each image they choose Select, Needs tweak, or Pass, adding a short note where it helps.","Feedback returns home. Every decision lands in your Feedback inbox and inside the campaign chat, grouped by round. An image marked *Needs tweak* or *Pass* can be sent straight into a revision draft tied to that frame.","Revise and re-share. Make the changes, star the new winners, and share again. Because the room link is stable, the next round shows up on the same URL the client already has."] },
      { type: 'callout', variant: "tip", text: "Send the same room link every round. The client never has to track a new URL — each new share just adds the latest round to the room they already bookmarked." },
      { type: 'h2', text: "What your client sees" },
      { type: 'ul', items: ["A clean review page — no login. The client opens the room link and lands on a warm, paper-styled page with your work front and center and none of the app chrome. There's nothing to sign up for.","A decision on every image. Each frame carries its own Select / Needs tweak / Pass controls and a note field, so feedback is specific and actionable instead of one vague reply for the whole batch.","Concept rounds, too. For text-first approval before you render, concept rounds show focused concept cards — the concept statement, reference thumbnails, decision buttons, and a field to suggest a replacement idea.","It works on a phone. The review room is built mobile-first — most clients open it on their phone, so decision buttons and note fields stay large, legible, and thumb-friendly."] },
      { type: 'callout', variant: "note", text: "The page keeps its own readable colors even if the client's browser is in dark mode, so review cards never wash out." }
      ], related: ["awa-chat"],
    }
  ],
  "getting-started": [
    {
      slug: "home",
      title: "Home",
      description: "Home is your studio's front door — favorite frames up top, the campaign you were just in one tap away, an action queue for anything waiting on you, and every brand within reach.",
      updatedAt: "2026-06-13",
      blocks: [
      { type: 'img', src: "/assets/images/landing-v4/home/hero.png", alt: "The Dezygn home dashboard with favorites, action queue, and brands", caption: "Your studio, at a glance." },
      { type: 'h2', text: "Overview" },
      { type: 'p', text: "Home is the front door to your studio. Instead of a blank start page, it shows what you actually care about the moment you land: the frames you've starred, the campaign you were just in, anything waiting on your review, and all your brands within reach. From here you're one tap from every part of the app." },
      { type: 'h2', text: "What you can do here" },
      { type: 'ul', items: ["Reopen your best frames. The Favorites mosaic up top holds every frame you've starred. Click a tile to jump straight back to the campaign it lives in, or open the full Gallery.","Clear your action queue. The Action queue gathers review rounds and concept decisions that need you. Each row opens the feedback or campaign behind it.","Pick up where you left off. Your most recently opened campaigns sit ready below — one tap back into any workspace.","Jump to a brand. The Brands row shows a thumbnail wall and campaign count per brand, so you can dive into the right one fast."] },
      { type: 'callout', variant: "tip", text: "New here? Home also runs the first-mile setup checklist and a guided product tour — finish those once and they step aside." }
      ], related: ["brands","gallery"],
    }
  ],
  "ingredients": [
    {
      slug: "ingredients",
      title: "Ingredients",
      description: "A per-brand library of the products, logos, and references Awa actually uses — upload them, import from a URL, or draw your own, then drop them into any prompt with @.",
      updatedAt: "2026-06-13",
      blocks: [
      { type: 'img', src: "/assets/images/landing-v4/ingredients/hero.png", alt: "The Ingredients tab — a masonry mosaic of product and reference images for the brand", caption: "Your brand's asset library, on the canvas." },
      { type: 'h2', text: "Overview" },
      { type: 'p', text: "Ingredients are the real things your shots are built from — your product photos, logos, and reference images. The Ingredients tab is a brand-wide library that lives inside every campaign workspace: whatever you add belongs to the brand named in the header and is available to every campaign under it. When you attach an ingredient to a prompt, Awa builds the shot around the actual asset, so a real product photo beats a paragraph of description every time." },
      { type: 'h2', text: "How it works" },
      { type: 'p', text: "Open any campaign and switch to the Ingredients tab. The whole tab is a drop target — drag files anywhere onto it (a dashed purple overlay confirms the drop). The images themselves are the star: a gallery-style masonry mosaic at their natural aspect ratios, with name, tags, and the info bubble revealed on hover. A compact header row carries the brand and count on the left, and search, the # Tags filter, Upload, URL import, Draw, and Select on the right." },
      { type: 'p', text: "Tags are yours to manage. Toggle # Tags to reveal a frequency-sorted chip strip (with per-tag counts and a +N more expander) and narrow the grid, or search by name. Nothing gets auto-tagged behind your back — the only path that writes AI tags is the explicit AI analyze action on a selection." },
      { type: 'p', text: "To use an ingredient, attach it to a message in the chat composer with @ (or the plus button). Awa builds the shot around exactly the assets you pick — up to 10 per message. You can also paste or drop an image straight onto the composer: it uploads as a brand ingredient and attaches itself, ready to send." },
      { type: 'h2', text: "Ways to add ingredients" },
      { type: 'ul', items: ["Upload — drag-and-drop anywhere on the tab, or click Upload. Up to 10 files per batch; each file up to 3.5 MB.","Import from a URL — the link icon opens a small popover with a URL field. Paste a Shopify product page (/products/…) to multi-select its images, or search and import from Pinterest.","Draw — open a focused canvas with pen, eraser, colors, size, undo/redo, and clear; name it and save it as an ingredient.","Save from a frame — promote a generated frame into an ingredient from the Create info drawer, so a result you love becomes a reusable reference.","Prep, then save — from an ingredient's detail drawer, Open Prep to crop, resize, remove the background, or upscale, then Save as new. The original source is always preserved."] },
      { type: 'callout', variant: "tip", text: "Attach a real product photo and a reference frame to the same message — Awa anchors composition to the reference and identity to the product. Two ingredients usually beat ten adjectives." }
      ], related: ["awa-chat","product-prep"],
    }
  ],
  "brands-campaigns": [
    {
      slug: "new-brand-import",
      title: "Brand Import",
      description: "Paste your website URL and Dezygn browses the live site to build a ready-to-use brand — colors, fonts, tone, and visual style — that Awa uses on every shot.",
      updatedAt: "2026-06-13",
      blocks: [
      { type: 'img', src: "/assets/images/landing-v4/new-brand-import/hero.png", alt: "New brand drawer with the import-from-website field", caption: "Paste a URL, get a brand." },
      { type: 'h2', text: "Overview" },
      { type: 'p', text: "Every project in Dezygn lives under a brand — the client whose colors, voice, and visual style Awa works in. Brand Import is the fastest way to create one: paste your website URL and Dezygn browses the live site, then fills a complete, editable brand profile for you. No questionnaires, no swatch-hunting. You can also build a brand entirely by hand — the import just saves you the setup. Either way, the brand you create becomes the context Awa uses on every shot." },
      { type: 'h2', text: "How it works" },
      { type: 'ul', items: ["Open New Brand. Start a new brand from the Brands area; the brand drawer opens with an *Import from website* field at the top.","Paste a URL. Drop in your site (e.g. https://yourbrand.com) and click *Analyze*. Any public site works.","It reads the real pages. Dezygn doesn't just grab a logo — it actually browses the live site: homepage, product pages, and about page. A deep read takes 60–120 seconds, and you'll see staged progress (\"Opening the site… / Reading pages & product photography… / Building your brand profile…\") while it works.","Review and edit. The form fills with evidence-based values — colors, font, archetype, audience, and a rich visual style. Every field stays editable, so adjust anything that doesn't feel right before saving.","Save, or do it manually. Saving stores the brand along with its brand fingerprint (the structured evidence Awa reads). No site to import? Just skip the URL field and fill the form yourself — the brand behaves identically."] },
      { type: 'callout', variant: "tip", text: "A deep read can take up to two minutes because Dezygn is genuinely browsing your pages, not screenshotting one. If a site can't be read, the import falls back automatically and you'll still get a starting point — and you can always edit from there." },
      { type: 'h2', text: "What gets imported" },
      { type: 'p', text: "From a single URL, Dezygn extracts:" },
      { type: 'ul', items: ["Colors — primary and secondary, pulled from the actual site and normalized to clean hex.","Fonts — the typographic style and feel of your brand.","Personality — a brand archetype (e.g. *Luxury / Premium*, *Disruptor / Edgy*, *Professional / Established*, *Value / Accessible*).","Target audience — who the brand speaks to, in plain language.","Visual style — a generation-ready description of your look: key materials, lighting, mood, and recurring visual elements, written so Awa can reproduce it.","Key visual elements — the signature details that make your photography recognizably yours."] },
      { type: 'p', text: "Everything imported is a starting point, not a verdict — it all stays editable in the preview before you save, and you can revise the brand anytime afterward." }
      ], related: ["awa-chat"],
    }
  ],
  "creating": [
    {
      slug: "prompt-canvas",
      title: "Prompt Canvas",
      description: "The prompt behind every frame, made readable — compare two frames word-by-word, edit the exact text, and resend it verbatim. Awa writes the words; you direct.",
      updatedAt: "2026-06-13",
      blocks: [
      { type: 'img', src: "/assets/images/landing-v4/prompt-canvas/hero.png", alt: "Prompt Canvas reading view inside the workspace", caption: "The prompt, on the canvas." },
      { type: 'h2', text: "Overview" },
      { type: 'p', text: "The Prompt Canvas makes the prompt a first-class citizen — the idea we call *the Tao of the Prompt*. Instead of a prompt buried in a chat bubble, it occupies the canvas: readable, comparable, editable, and resendable. You stay in control of the exact words behind every image, while Awa still does the heavy lifting of writing them." },
      { type: 'h2', text: "How It Works" },
      { type: 'ul', items: ["Open it. Use the *Prompt* toggle in the workspace action rail, or click the prompt excerpt in a frame's info drawer.","Read it. The prompt is laid out one sentence per line in a serif reading view; [image1]-style reference tokens render as inline chips. A *Raw* toggle shows the byte-exact text for copying.","Compare two frames. Select a second frame from the strip — the canvas shows both thumbnails and a single merged prompt with a word-level diff (green additions, red deletions), so you can see exactly what changed between two shots.","Edit and resend. Edit the raw text directly. The send button surfaces an \"N words changed\" badge and dispatches your wording verbatim, with prompt enhancement off, so what you wrote is what runs."] },
      { type: 'callout', variant: "tip", text: "Use *Compare* whenever two frames look close but one is clearly better — the diff usually reveals the one or two words doing the work." }
      ], related: ["awa-chat"],
    },
    {
      slug: "variant-board",
      title: "Variant Board",
      description: "A/B testing for your shots: lock the frame that's winning, spin off variants that each change a single ingredient or setting, then compare the grid and crown a new champion.",
      updatedAt: "2026-06-13",
      blocks: [
      { type: 'img', src: "/assets/images/landing-v4/variant-board/hero.png", alt: "Variant Board with a locked champion frame", caption: "Champion locked, ready for variants." },
      { type: 'h2', text: "Overview" },
      { type: 'p', text: "The Variant Board turns the control-vs-variant method into a workspace surface. Instead of generating ten frames and hoping one lands, you pick the frame that's already winning, lock it as your champion (the control), and spin off variants that each change exactly *one* thing. It's A/B testing for image generation: a clean control, a single variable, and a grid that actually tells you what's better." },
      { type: 'h2', text: "How it works" },
      { type: 'ul', items: ["Open the board. Select a frame, then hit the grid icon in the frame's action rail. The board opens to a contact sheet of every frame in the campaign — starred frames are badged.","Crown a champion. Pick the frame that's clearly working and *Promote to Champion*. It locks on the left as your control: the image plus an editable control prompt derived from how it was made.","Add variant rows. The composer is a one-variable chip picker — Lighting, Background/Surface, Action, Subject, Camera, Style, Brand accent — plus a one-line change description. Pick one variable, describe the change concretely (real ratios beat vague words).","Generate the grid. Each row regenerates from the champion frame, changing only its single clause. Fresh results auto-link to the oldest pending row, and any chat-side run can be pulled onto the board with one click.","Crown the winner. Compare the variants against the locked control. When one wins, *Save champion as Recipe* to reuse that look anywhere — or promote a stronger frame to champion and run another round."] },
      { type: 'callout', variant: "tip", text: "Change one variable per row. If you swap the lighting *and* the background in the same variant, you won't know which one moved the needle." },
      { type: 'h2', text: "When to use it" },
      { type: 'p', text: "Reach for the Variant Board once you have a frame that's *close* — the composition works but you're not sure about the lighting, the surface, or the camera angle. It's the disciplined alternative to re-rolling the whole prompt: keep everything that's right, isolate the one thing you're unsure about, and let the side-by-side decide. When you've found the winning combination, consolidate it into a Recipe so the look becomes repeatable." }
      ], related: ["prompt-canvas","awa-chat"],
    }
  ],
  "account-billing": [
    {
      slug: "settings",
      title: "Settings",
      description: "Settings is your account hub: see your plan and credits, manage your team and share-page watermark, edit your profile, grab your referral link, and reach support.",
      updatedAt: "2026-06-13",
      blocks: [
      { type: 'img', src: "/assets/images/landing-v4/settings/hero.png", alt: "The Dezygn settings page with Plan, Team, Profile, Referrals, and Support tabs", caption: "Your account hub." },
      { type: 'h2', text: "Overview" },
      { type: 'p', text: "Settings is your account hub. It's a full-width tabbed page that gathers everything about your account in one place: your plan and credits, your team and share-page watermark, your profile, your referral link, and a way to reach support. Each tab is deep-linkable (the active tab shows in the URL as ?tab=), so you can jump straight to the part you need." },
      { type: 'h2', text: "What you can do here" },
      { type: 'ul', items: ["Plan & credits. See your subscription, your monthly, flex, and total credit balances, buy Flex-pack top-ups, review plan limits and recent credit activity, and open the billing portal.","Team. Edit the team name, copy an invite link, manage the member list, and set your share-page watermark — upload or replace the image and toggle it on by default for shared galleries.","Profile. Change your display name and password, and manage your Upwork application profile used by the Apply Kit.","Referrals. Copy your referral link and track total, converted, and pending referrals.","Support. Reach the Help Center or email support directly."] },
      { type: 'callout', variant: "note", text: "Billing actions, the team name, and the watermark are owner-only. Members see the tabs but can't change team-level settings." }
      ],
    }
  ]
};
